---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers

- name: configuration
  hosts: all
  gather_facts: false
  become: true

  tasks:
  - name: enable repos
    template:
      src: ./open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644


- name: Deploy HAProxy
  hosts: frontends
  gather_facts: false
  become: true
  roles:
    - role: haproxy


- name: Deploy tomcat
  hosts: apps
  gather_facts: false
  become: true
  roles:
    - role: tomcat



#
#- name: index.html on App1
#  hosts: app1.b3ea.internal
#  gather_facts: false
#  become: true
#
#  tasks:
#  - name: copy static index.html to tomcat webapps/ansible/index.html
#    template:
#      src: index.html.app1
#      dest: /usr/share/tomcat/webapps/ansible/index.html


#- name: index.html on App2
#  hosts: app2.b3ea.internal
#  gather_facts: false
#  become: true
#
#  tasks:
#  - name: copy static index.html to tomcat webapps/ansible/index.html
#    template:
#      src: index.html.app2
#      dest: /usr/share/tomcat/webapps/ansible/index.html




- name: deploy postgres
  hosts: 
    - apps
    - appdbs
  gather_facts: false
  become: true
  roles:
    - role: postgres


- name: deploy apache
  hosts: apps
  gather_facts: false
  become: true
  roles:
    - role: apache
  