---
- name: Install tomcat
  package:
    name: tomcat
    state: latest
  notify:
    - Enable tomcat

- name: Create Ansible tomcat directory
  file:
    path: "{{ tomcat_dir }}"
    state: directory

- name: Copy static index.html to tomcat webapps/ansible/index.html
  template:
    src: index.html.j2
    dest: "{{ tomcat_dir }}/index.html"
    mode: "{{ tomcat_mode }}"
  notify:
    - Start tomcat